GAMMAFEST/Models/Evento.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace GAMMAFEST.Models
{
    public class Evento
    {
        [Key]
        public int EventoId { get; set; }
        [DataType(DataType.DateTime)]
        public DateTime FechaInicioEvento { get; set; }
        public string NombreEvento { get; set; }
        public string NombreImagen { get; set; }
        [NotMapped]
        public IFormFile ArchivoImagen { get; set; }
        public string Descripcion { get; set; }
        public string Protocolos { get; set; }
        public int IdUser { get; set; }
        public float AforoMaximo { get; set; }
        public float PrecioEntradaUnit { get; set; }
        
        [ForeignKey("IdUser")]
        public virtual UserPromotor? UserPromotor { get; set; }
    }
}

GAMMAFEST/Controllers/EventoController.cs
using GAMMAFEST.Filters;
using GAMMAFEST.Models;
using GAMMAFEST.Repositorio;
using Microsoft.AspNetCore.Mvc;

namespace GAMMAFEST.Controllers
{
    public class EventoController : Controller
    {
        public readonly IEventoRepositorio repositorio;
        public readonly IWebHostEnvironment _hostEnvironment;

        public EventoController(IEventoRepositorio repositorio, IWebHostEnvironment hostEnvironment)
        {
            this.repositorio = repositorio;
            _hostEnvironment = hostEnvironment;
        }

        [AuthorizeUsers(Policy ="ADMINISTRADORES")]
        public IActionResult CrearEvento(int id) {

            ViewBag.fechaNow = DateTime.Now;
            ViewBag.idPromTemp = id;
            ViewData["Verificado"] = "Encontrado";
            return View();
        }
        public string SubirArchivo(Evento evento)
        {
            string? nArchivo = null;
            string? temp1 = null;
            if (evento.ArchivoImagen != null)
            {
                string path = _hostEnvironment.WebRootPath;
                nArchivo = Path.GetFileNameWithoutExtension(evento.ArchivoImagen.FileName);
                string x = Path.GetExtension(evento.ArchivoImagen.FileName);
                evento.NombreImagen = nArchivo + x;
                temp1 = nArchivo + x;
                string z = Path.Combine(path + "/imageBD/", nArchivo + x);

                if (!Directory.Exists(path+"/imageBD"))
                {
                    Directory.CreateDirectory(path + "/imageBD");
                }

                using (var fileStream = new FileStream(z, FileMode.Create))
                {
                    evento.ArchivoImagen.CopyTo(fileStream);
                }
            }
            return temp1;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CrearEvento(Evento evento) {
            if (ModelState.IsValid)
            {
                if (evento.FechaInicioEvento <= DateTime.Now)
                    ViewData["MENSAJE"] = "La fecha ingresada no puede ser menor a la fecha actual";
                
                else
                {
                    evento.NombreImagen = SubirArchivo(evento);
                    //evento.UserPromotor = promotorRepositorio.ObtenerUserById(id);
                    repositorio.CrearEvento(evento);
                    return RedirectToAction("Index", "Home");
                }
            }
            return View(evento);
        }

        [AuthorizeUsers]
        [HttpGet]
        public IActionResult IndexEvento(int? id, int id2)
        {
            var evento = repositorio.ObtenerSoloEventoConPromotor((int)id);
            ViewBag.idTemp = id2.ToString();
            return View(evento);
        }


        [HttpGet]
        public IActionResult ListarEventos(int temp, int idUser) {
            List<Evento> list = new List<Evento>();
            switch (temp) {
                case 1: list = repositorio.ObtenerTodosEventosByUserIdPasados(idUser, 1); break;

                case 2: list = repositorio.ObtenerTodosEventosByUserIdPasados(idUser, 2); break;

                case 3: list = repositorio.ObtenerTodosEventosByUserIdPasados(idUser, 3); break;
            }

            ViewBag.temp = temp;
            ViewBag.id = idUser;
            return View(list);
        }
    }
}

GAMMAFEST/Controllers/PromotorController.cs
using GAMMAFEST.Models;
using GAMMAFEST.Repositorio;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace GAMMAFEST.Controllers
{
    public class PromotorController : Controller
    {
        private IPromotorRepositorio rep;
        private IEventoRepositorio eventoRepositorio;
        public PromotorController(IPromotorRepositorio rep, IEventoRepositorio eventoRepositorio)
        {
            this.rep = rep;
            this.eventoRepositorio = eventoRepositorio;
        }

        //REGISTRO DE PROMOTORES
        
        public IActionResult RegistroPromotor() {
            return View();
        }

        [HttpPost]
        public IActionResult RegistroPromotor(string email, string password, string nombre, string apellidos, string tipo) {

            bool registrado = this.rep.RegistrarUsuario(email, password, nombre, apellidos, tipo);
            if (registrado)
                ViewData["MENSAJE"] = "Usuario registrado con exito";
            else 
                ViewData["MENSAJE"] = "Lo sentimos, el correo electrónico ya existe en nuestra base de datos";
            
            return View();
        }

        //
        //
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(string email, string password)
        {

            UserPromotor promotor = this.rep.LogInUsuario(email, password);
            if (promotor == null)
            {
                ViewData["MENSAJE"] = "No tienes credenciales correctas";
                return View();
            }
            else
            {
                //DEBEMOS CREAR UNA IDENTIDAD (name y role)
                //Y UN PRINCIPAL
                //DICHA IDENTIDAD DEBEMOS COMBINARLA CON LA COOKIE DE 
                //AUTENTIFICACION
                ClaimsIdentity identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme, ClaimTypes.Name, ClaimTypes.Role);
                //TODO USUARIO PUEDE CONTENER UNA SERIE DE CARACTERISTICAS
                //LLAMADA CLAIMS.  DICHAS CARACTERISTICAS PODEMOS ALMACENARLAS
                //DENTRO DE USER PARA UTILIZARLAS A LO LARGO DE LA APP
                Claim claimUserName = new Claim(ClaimTypes.Name, promotor.Nombre);
                Claim claimRole = new Claim(ClaimTypes.Role, promotor.tipoUsuario);
                Claim claimIdUsuario = new Claim("IdUser", promotor.IdUser.ToString());
                Claim claimEmail = new Claim("EmailUsuario", promotor.Email);

                identity.AddClaim(claimUserName);
                identity.AddClaim(claimRole);
                identity.AddClaim(claimIdUsuario);
                identity.AddClaim(claimEmail);

                ClaimsPrincipal userPrincipal = new ClaimsPrincipal(identity);
                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, userPrincipal, new AuthenticationProperties
                {
                    ExpiresUtc = DateTime.Now.AddMinutes(45)
                });

                return RedirectToAction("Index", "Home", new {id=promotor.IdUser});
            }
        }
        [HttpGet]
        public IActionResult Init()
        {
            var user = rep.GetLoggedUser();
            if (user != null)
            {
                var eventos = eventoRepositorio.ObtenerTodosEventosByUserId(user.IdUser).Count();
                ViewBag.eventos = eventos;
                ViewBag.nombre = user.Nombre;
                ViewBag.apellido = user.Apellido;
                ViewBag.mail = user.Email;
                ViewBag.idUser = user.IdUser;


                if (user.tipoUsuario == "ADMIN")
                    ViewBag.tipo = "PROMOTOR";

                else
                    ViewBag.tipo = "USUARIO";
            }


            

            return View();

        }

        public async Task<IActionResult> LogOut()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Home");
        }
    }
}

GAMMAFEST/Controllers/RegistroAsistenciaController.cs
using GAMMAFEST.Models;
using GAMMAFEST.Repositorio;
using IronBarCode;
using Microsoft.AspNetCore.Mvc;
using SixLabors.Fonts.Tables.TrueType;

namespace GAMMAFEST.Controllers
{
    public class RegistroAsistenciaController : Controller
    {
        bool encontrado = false;
        public readonly IRegistroAsistenciaRepositorio repositorio;
        public readonly IPromotorRepositorio promotorRepositorio;
        public readonly IEntradaRepositorio entradaRepositorio;
        readonly IEventoRepositorio eventoRepositorio;

        public readonly IWebHostEnvironment _hostEnvironment;

        public RegistroAsistenciaController(IRegistroAsistenciaRepositorio repositorio,  IWebHostEnvironment hostEnvironment, IPromotorRepositorio promotorRepositorio, IEventoRepositorio eventoRepositorio, IEntradaRepositorio entradaRepositorio)
        {
            this.repositorio = repositorio;
            _hostEnvironment = hostEnvironment;
            this.promotorRepositorio = promotorRepositorio;
            this.eventoRepositorio = eventoRepositorio;
            this.entradaRepositorio = entradaRepositorio;
        }

        public IActionResult LeerQR()
        {

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult LeerQR(RegistroAsistencia qr, int idEvento)
        {
            if (ModelState.IsValid)
            {
                qr.NombreImagen = repositorio.SubirArchivo(qr);

                var path = _hostEnvironment.WebRootPath;

                var fullPath = path + "\\imageQR\\"+qr.NombreImagen;

                string s = repositorio.Lectura(fullPath);

                string[] subs = s.Split('~');

                var ticketId = subs[0].Remove(0, 13);

                qr.EntradaId = int.Parse(ticketId);

                var entrada = entradaRepositorio.ObtenerEntrada(qr.EntradaId);

                var registros = repositorio.registros();

                var evento = eventoRepositorio.ObtenerSoloEvento(entrada.EventoId);

                var user = promotorRepositorio.ObtenerUserById(entrada.IdUser);


                if (System.IO.File.Exists(fullPath))
                    System.IO.File.Delete(fullPath);

                if (idEvento != evento.EventoId)
                    ViewData["MENSAJE"] = "Lo sentimos, el QR no pertenece a este evento";
                else
                {
                    if (registros.Count() > 0)
                    {
                        for (int i = 1; i <= registros.Count(); i++)
                        {
                            if (qr.EntradaId == registros[i-1].EntradaId)
                            {
                                ViewData["MENSAJE"] = "Lo sentimos, su entrada ya ha sido registrada";
                                encontrado = false;
                            }
                            else
                                encontrado = true;
                        }
                    }
                    else
                        encontrado = true;

                    if (encontrado) {
                        ViewData["MENSAJE"] = "Felicidades, la asistencia fue registrada con éxito";
                        repositorio.SubirQR(qr);
                    }
                }

                //var tempString = 

                ViewBag.ticket = qr.EntradaId;
                ViewBag.evento = evento.NombreEvento;
                ViewBag.usuario = user.Nombre;

            }
            return View(qr);
        }

        [HttpGet]
        public IActionResult ListaAsistentes(int idEvento) {
            var evento = eventoRepositorio.ObtenerSoloEvento(idEvento);
            var entrada = entradaRepositorio.ObtenerEntradasByEventoId(evento.EventoId);

            List<UserPromotor> user= new List<UserPromotor>();

            for (int i = 0; i < entrada.Count(); i++)
            {
                if (entrada[i].EntradaId == entrada[i].IdCantidad)
                    user.Add(promotorRepositorio.ObtenerUserById(entrada[i].IdUser));
            }

            ViewBag.usuarios = user;
            ViewBag.evento = evento.NombreEvento;

            var registro = repositorio.ListarAsistentes(entrada);

            return View(registro);
        }
    }
}

GAMMAFEST/Views/Evento/CrearEvento.cshtml
@model GAMMAFEST.Models.Evento
@using System.Security.Claims;

@{
    ViewData["Title"] = "CrearEvento";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Registro de Evento</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--===============================================================================================-->
    <!--<link rel="icon" type="image/png" href="images/icons/favicon.ico"/>
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/css/dist/css/bootstrap.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/fonts/font-awesome-4.7.0/css/font-awesome.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/vendor/animate/animate.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/vendor/css-hamburgers/hamburgers.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/vendor/select2/select2.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="/css/util.css">
    <link rel="stylesheet" type="text/css" href="/css/main.css">
    <!--===============================================================================================-->
</head>
<body>

    <div class="limiter">
        <div class="container-login100">
            <div class="wrap-login100">
                <div class="login100-pic js-tilt" data-tilt>
                    <img src="~/image/logo_black.png" alt="IMG">
                    @if (ViewData["MENSAJE"] != null)
                    {
                        <br>
                        <br>
                        <div class=" alert alert-danger">
                            @ViewData["MENSAJE"]
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    }
                </div>
                <form class="login100-form validate-form" method="post" asp-action="CrearEvento" enctype="multipart/form-data">
                    <span class="login100-form-title">
                        GAMMA-FEST
                    </span>

                    <span class="login100-form-title">
                        Registrar Evento
                    </span>

                    <div class="wrap-input100 validate-input">
                        <textarea asp-for="Descripcion" id="summernote1" class="input100" autocomplete="username" aria-required="true" placeholder="Descripcion"></textarea>
                        <span asp-validation-for="Descripcion"></span>
                    </div>

                    <div class="wrap-input100 validate-input">
                        <input asp-for="NombreEvento" class="input100" autocomplete="username" aria-required="true" placeholder="Nombres:" />
                        <span asp-validation-for="NombreEvento"></span>
                    </div>

                    <div class="wrap-input100 validate-input">
                        <input asp-for="Protocolos" class="input100" aria-required="true" placeholder="Protocolo:" />
                        <span asp-validation-for="Protocolos"></span>
                    </div>

                    <input type="hidden" asp-for="NombreImagen" value="a1" />

                    <div class="wrap-input100 validate-input">
                        <input type="datetime-local" asp-for="FechaInicioEvento" id="fechaEvento" class="input100" aria-required="true" placeholder="Fecha del Evento" />
                        <span asp-validation-for="FechaInicioEvento"></span>
                    </div>

                    <input asp-for="IdUser" value=@ViewBag.idPromTemp>

                    <div class="wrap-input100 validate-input">
                        <input asp-for="ArchivoImagen" class="input100" accept="image/*" />
                        <span asp-validation-for="ArchivoImagen" class="text-danger"></span>
                    </div>

                    <div class="wrap-input100 validate-input">
                        <input asp-for="AforoMaximo" class="input100" id="aforoMaximo" aria-required="true" placeholder="Aforo Máximo" />
                        <span asp-validation-for="AforoMaximo"></span>
                    </div>

                    <div class="wrap-input100 validate-input">
                        <input asp-for="PrecioEntradaUnit" class="input100" id="precioEntrada" aria-required="true" placeholder="Precio de la entrada (S/.)" />
                        <span asp-validation-for="PrecioEntradaUnit"></span>
                    </div>

                    <div class="container-login100-form-btn">
                        <div class="form-group">
                            <input type="submit" id="create" value="Almacenar Evento" class="cta3" />
                        </div>
                    </div>

                    <div>
                        <a asp-controller="Home" asp-action="Index">
                           Regresar
                        </a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</body>
</html>

GAMMAFEST/Views/Evento/IndexEvento.cshtml
@model GAMMAFEST.Models.Evento
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

@{
	ViewData["Title"] = "IndexEvento";
}

<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login V1</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<!--<link rel="icon" type="image/png" href="images/icons/favicon.ico"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="~/css/dist/css/bootstrap.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="~/fonts/font-awesome-4.7.0/css/font-awesome.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="~/vendor/animate/animate.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="~/vendor/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="~/vendor/select2/select2.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/css/util.css">
	<link rel="stylesheet" type="text/css" href="/css/main.css">
<!--===============================================================================================-->
</head>
<body>
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<div class="login100-pic js-tilt" data-tilt>
					<img src="@Url.Content("~/imageBD/"+Model.NombreImagen)" alt="IMG">
					<span class="login100-form-title">
						@Model.NombreEvento.ToUpper()
					</span>

					<div class="accordion" id="accordionExample">
						<div class="accordion-item">
							<h2 class="accordion-header" id="headingOne">
								<button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
									<strong>
										<em>Protocolos de Seguridad para este Evento</em>
									</strong>
								</button>
							</h2>
							<div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
								<div class="accordion-body">
									<strong>El evento cumple con los siguientes protocolos</strong>
									<ul>
										<li type="circle">@Model.Protocolos</li>
									</ul>
								</div>
							</div>
						</div>
						<div class="accordion-item">
							<h2 class="accordion-header" id="headingTwo">
								<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
									<strong>
										<em>Ubicación y Fecha del Evento</em>
									</strong>
								</button>
							</h2>
							<div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
								<div class="accordion-body">
									<strong>Ubicación</strong>
									<ul>
										<li>Ubicación Ejemplo</li>
									</ul>
									<strong>Fecha de Inicio</strong>
									<ul>
										<li>Día: @Model.FechaInicioEvento.ToString("d")</li>
										<li>Hora: @Model.FechaInicioEvento.ToString("H : m")</li>
									</ul>
								</div>
							</div>
						</div>
						<div class="accordion-item">
							<h2 class="accordion-header" id="headingThree">
								<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
										<strong>
											<em>Organizador</em>
										</strong>
								</button>
							</h2>
							<div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
								<div class="accordion-body">
									<strong>Detalles del Promotor</strong>
										<ul>
											<li><strong>Nombres:</strong> @Model.UserPromotor.Nombre</li>
											<li><strong>Apellidos:</strong> @Model.UserPromotor.Apellido</li>
										</ul>
										<strong>Contacto</strong>
										<ul>
											<li><strong>Teléfono:</strong>943573485</li>
											<li><strong>Correo Electrónico:</strong>@Model.UserPromotor.Email</li>
										</ul>
								</div>
							</div>
						</div>

						<div class="accordion-item">
							<h2 class="accordion-header" id="headingTree">
								<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTree" aria-expanded="false" aria-controls="collapseTree">
									<strong>
										<em>Disponibilidad, Estado y Precio del Evento</em>
									</strong>
								</button>
							</h2>
							<div id="collapseTree" class="accordion-collapse collapse" aria-labelledby="headingTree" data-bs-parent="#accordionExample">
								<div class="accordion-body">
									<strong>Disponibilidad</strong>
									<ul>
										<li>Aforo Disponible: @Model.AforoMaximo</li>
									</ul>
									<strong>Estado del Evento</strong>
									<ul>
										<li>Estado: Terminado (Ejemplo)</li>
									</ul>
									<strong>Precio de la entrada</strong>
									<ul>
										<li>@Model.PrecioEntradaUnit</li>
									</ul>
								</div>
							</div>
						</div>

					</div>
				</div>
				
				<form class="login100-form validate-form" id="account" method="post">
					<div class="login100-pic js-tilt" data-tilt>
							<span class="login100-form-title">
								GAMMA-FEST
							</span>

							<span class="login100-form-title">
								Detalles del Evento
							</span>
						@Model.Descripcion
						Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut asd
					</div>
					<br>
						@{
							var par = new Dictionary<string, string> {
								{"idEvento", Model.EventoId.ToString()},
								{"idUser", ViewBag.idtemp}
							};
						}

						<div class="container-login100-form-btn">
							<button class="login100-form-btn" id="venta" type="submit">
								<a class="login100-form-btn" asp-controller="Entrada" asp-action="VentaEntrada" asp-all-route-data="par">
									Asistir a este evento
								</a>
							</button>
						</div>

						<div class="container-login100-form-btn">
							<button class="login100-form-btn" id="regresar" type="submit">
								<a class="login100-form-btn" asp-controller="Home" asp-action="Index">
									Regresar
								</a>
							</button>
						</div>

						@if (SignInManager.IsSignedIn(User))
						{
							<div class="container-login100-form-btn">
								<button class="login100-form-btn" id="listado" type="submit">
									<a class="login100-form-btn" asp-controller="Usuario" asp-action="IndexUsuario" asp-route-Id="@Model.EventoId">
										Lista de Asistentes:
									</a>
								</button>
							</div>
						}
				</form>
			</div>
		</div>
	</div>
	}
</body>
</html>

GAMMAFEST/Views/Evento/ListarEventos.cshtml
@model IEnumerable<GAMMAFEST.Models.Evento>

@{
    ViewData["Title"] = "ListarEventos";
}

<!DOCTYPE html>
<html lang="en">
<head>
	<title>Listado de Eventos</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<!--<link rel="icon" type="image/png" href="images/icons/favicon.ico"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="~/css/dist/css/bootstrap.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="~/fonts/font-awesome-4.7.0/css/font-awesome.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="~/vendor/animate/animate.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="~/vendor/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="~/vendor/select2/select2.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/css/util.css">
	<link rel="stylesheet" type="text/css" href="/css/main.css">
<!--===============================================================================================-->
</head>
<body>
	<div class="limiter">
		<div class="container-login100">
            <div class="wrap-login100">

                <div style="position: relative;
  top: -100px;">
                    <table class="table mb-0">
                        <thead>
                            <tr>
                                <th id="numero">
                                    #
                                </th>
                                <th id="fecha">
                                    FECHA
                                </th>
                                <th id="evento">
                                    EVENTO
                                </th>
                                <th id="aforo">
                                    AFORO
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @item.EventoId
                                    </td>
                                    <td>
                                        @item.FechaInicioEvento
                                    </td>
                                    <td id="Evento1">
                                        @item.NombreEvento
                                    </td>
                                    <td>
                                        @item.AforoMaximo
                                    </td>
                                    <td>
                                        @if (ViewBag.temp == 1)
                                        {
                                            @*
                                            <a asp-action="Delete" class="btn btn-danger" asp-route-id="@item.EventoId">Eliminar</a>*@
                                            <a asp-action="ListaAsistentes" asp-controller="RegistroAsistencia" class=" btn btn-dark" asp-route-idEvento="@item.EventoId">Ver Lista de asistentes</a>
                                        }
                                        @if (ViewBag.temp == 2)
                                        {
                                            @*
                                            <a asp-action="Edit" class="btn btn-secondary" asp-route-id="@item.EventoId">Editar</a>
                                            <a asp-action="Delete" class="btn btn-danger" asp-route-id="@item.EventoId">Eliminar</a>*@
                                            <a type="button" class="btn btn-dark" asp-controller="RegistroAsistencia" asp-action="LeerQR" asp-route-idEvento="@item.EventoId">Registrar Asistencia</a>
                                            <a asp-action="ListaAsistentes" asp-controller="RegistroAsistencia" class=" btn btn-dark" asp-route-idEvento="@item.EventoId">Ver Lista de asistentes</a>
                                        }

                                        @*@if (ViewBag.temp == 3)
                                        {
                                            <a asp-action="Edit" class="btn btn-secondary" asp-route-id="@item.EventoId">Editar</a>
                                            <a asp-action="Delete" class="btn btn-danger" asp-route-id="@item.EventoId">Eliminar</a>
                                        }*@
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                    <a type="button" class="btn btn-dark" asp-controller="Promotor" asp-action="Init">Regresar</a>
                </div>
                
		    </div>
	    </div>
    </div>
</body>
</html>